import { Border } from "../model/Border";
import { Role } from "../model/Role";
import { Square } from "../model/Square";


const squares = [
    new Square(0, 0, 0, new Border(Border.TOP | Border.LEFT)),
    new Square(1, 0, 1, new Border(Border.TOP | Border.RIGHT)),
    new Square(2, 0, 2, new Border(Border.TOP | Border.LEFT)),
    new Square(3, 0, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(4, 0, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(5, 0, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(6, 0, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(7, 0, 7, new Border(Border.TOP | Border.BOTTOM)),
    new Square(8, 0, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(9, 0, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(10, 0, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(11, 0, 11, new Border(Border.TOP | Border.BOTTOM)),
    new Square(12, 0, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(13, 0, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(14, 0, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(15, 0, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(16, 0, 16, new Border(Border.TOP | Border.BOTTOM)),
    new Square(17, 0, 17, new Border(Border.TOP | Border.BOTTOM)),
    new Square(18, 0, 18, new Border(Border.TOP | Border.RIGHT)),
    new Square(19, 0, 19, new Border(Border.TOP | Border.LEFT)),
    new Square(20, 0, 20, new Border(Border.TOP | Border.BOTTOM)),
    new Square(21, 0, 21, new Border(Border.TOP | Border.BOTTOM)),
    new Square(22, 0, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(23, 0, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(24, 0, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(25, 0, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(26, 0, 26, new Border(Border.TOP | Border.BOTTOM)),
    new Square(27, 0, 27, new Border(Border.TOP | Border.RIGHT)),
    new Square(28, 1, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(29, 1, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(30, 1, 2, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(31, 1, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(32, 1, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(33, 1, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(34, 1, 6, new Border(Border.TOP | Border.RIGHT)),
    new Square(35, 1, 7, new Border(Border.TOP | Border.LEFT)),
    new Square(36, 1, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(37, 1, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(38, 1, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(39, 1, 11, new Border(Border.TOP | Border.BOTTOM)),
    new Square(40, 1, 12, new Border(Border.TOP | Border.RIGHT)),
    new Square(41, 1, 13, new Border(Border.TOP | Border.LEFT)),
    new Square(42, 1, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(43, 1, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(44, 1, 16, new Border(Border.TOP | Border.BOTTOM)),
    new Square(45, 1, 17, new Border(Border.TOP | Border.BOTTOM)),
    new Square(46, 1, 18, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(47, 1, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(48, 1, 20, new Border(Border.TOP | Border.LEFT)),
    new Square(49, 1, 21, new Border(Border.TOP | Border.BOTTOM)),
    new Square(50, 1, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(51, 1, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(52, 1, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(53, 1, 25, new Border(Border.TOP | Border.RIGHT)),
    new Square(54, 1, 26, new Border(Border.TOP | Border.LEFT)),
    new Square(55, 1, 27, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(56, 2, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(57, 2, 1, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(58, 2, 2, new Border(Border.TOP | Border.BOTTOM)),
    new Square(59, 2, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(60, 2, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(61, 2, 5, new Border(Border.TOP | Border.RIGHT)),
    new Square(62, 2, 6, new Border(Border.LEFT | Border.RIGHT)),
    new Square(63, 2, 7, new Border(Border.LEFT | Border.RIGHT)),
    new Square(64, 2, 8, new Border(Border.TOP | Border.LEFT)),
    new Square(65, 2, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(66, 2, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(67, 2, 11, new Border(Border.TOP | Border.RIGHT)),
    new Square(68, 2, 12, new Border(Border.LEFT | Border.RIGHT)),
    new Square(69, 2, 13, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(70, 2, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(71, 2, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(72, 2, 16, new Border(Border.TOP | Border.BOTTOM)),
    new Square(73, 2, 17, new Border(Border.TOP | Border.BOTTOM)),
    new Square(74, 2, 18, new Border(Border.TOP | Border.RIGHT)),
    new Square(75, 2, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(76, 2, 20, new Border(Border.LEFT)),
    new Square(77, 2, 21, new Border(Border.TOP | Border.BOTTOM)),
    new Square(78, 2, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(79, 2, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(80, 2, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(81, 2, 25, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(82, 2, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(83, 2, 27, new Border(Border.TOP | Border.LEFT | Border.RIGHT)),
    new Square(84, 3, 0, new Border(Border.LEFT)),
    new Square(85, 3, 1, new Border(Border.TOP | Border.BOTTOM)),
    new Square(86, 3, 2, new Border(Border.TOP | Border.BOTTOM)),
    new Square(87, 3, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(88, 3, 4, new Border(Border.TOP | Border.RIGHT)),
    new Square(89, 3, 5, new Border(Border.LEFT | Border.RIGHT)),
    new Square(90, 3, 6, new Border(Border.LEFT | Border.RIGHT)),
    new Square(91, 3, 7, new Border(Border.LEFT | Border.RIGHT)),
    new Square(92, 3, 8, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(93, 3, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(94, 3, 10, new Border(Border.TOP | Border.RIGHT)),
    new Square(95, 3, 11, new Border(Border.LEFT | Border.RIGHT)),
    new Square(96, 3, 12, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(97, 3, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(98, 3, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(99, 3, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(100, 3, 16, new Border(Border.TOP | Border.BOTTOM)),
    new Square(101, 3, 17, new Border(Border.TOP | Border.BOTTOM)),
    new Square(102, 3, 18, new Border(Border.NONE)),
    new Square(103, 3, 19, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(104, 3, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(105, 3, 21, new Border(Border.TOP | Border.LEFT)),
    new Square(106, 3, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(107, 3, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(108, 3, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(109, 3, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(110, 3, 26, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(111, 3, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(112, 4, 0, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(113, 4, 1, new Border(Border.TOP | Border.BOTTOM)),
    new Square(114, 4, 2, new Border(Border.TOP | Border.BOTTOM)),
    new Square(115, 4, 3, new Border(Border.TOP | Border.RIGHT)),
    new Square(116, 4, 4, new Border(Border.LEFT | Border.RIGHT)),
    new Square(117, 4, 5, new Border(Border.LEFT | Border.RIGHT)),
    new Square(118, 4, 6, new Border(Border.LEFT | Border.RIGHT)),
    new Square(119, 4, 7, new Border(Border.LEFT | Border.RIGHT)),
    new Square(120, 4, 8, new Border(Border.TOP | Border.LEFT)),
    new Square(121, 4, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(122, 4, 10, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(123, 4, 11, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(124, 4, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(125, 4, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(126, 4, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(127, 4, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(128, 4, 16, new Border(Border.TOP | Border.BOTTOM)),
    new Square(129, 4, 17, new Border(Border.TOP | Border.BOTTOM)),
    new Square(130, 4, 18, new Border(Border.RIGHT)),
    new Square(131, 4, 19, new Border(Border.TOP | Border.LEFT)),
    new Square(132, 4, 20, new Border(Border.RIGHT)),
    new Square(133, 4, 21, new Border(Border.LEFT | Border.RIGHT)),
    new Square(134, 4, 22, new Border(Border.TOP | Border.LEFT)),
    new Square(135, 4, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(136, 4, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(137, 4, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(138, 4, 26, new Border(Border.TOP | Border.BOTTOM)),
    new Square(139, 4, 27, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(140, 5, 0, new Border(Border.TOP | Border.LEFT)),
    new Square(141, 5, 1, new Border(Border.TOP | Border.RIGHT)),
    new Square(142, 5, 2, new Border(Border.TOP | Border.LEFT | Border.RIGHT)),
    new Square(143, 5, 3, new Border(Border.LEFT | Border.RIGHT)),
    new Square(144, 5, 4, new Border(Border.LEFT | Border.RIGHT)),
    new Square(145, 5, 5, new Border(Border.LEFT | Border.RIGHT)),
    new Square(146, 5, 6, new Border(Border.LEFT | Border.RIGHT)),
    new Square(147, 5, 7, new Border(Border.LEFT | Border.RIGHT)),
    new Square(148, 5, 8, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(149, 5, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(150, 5, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(151, 5, 11, new Border(Border.TOP | Border.BOTTOM)),
    new Square(152, 5, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(153, 5, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(154, 5, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(155, 5, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(156, 5, 16, new Border(Border.TOP | Border.BOTTOM)),
    new Square(157, 5, 17, new Border(Border.TOP | Border.RIGHT)),
    new Square(158, 5, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(159, 5, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(160, 5, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(161, 5, 21, new Border(Border.LEFT | Border.RIGHT)),
    new Square(162, 5, 22, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(163, 5, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(164, 5, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(165, 5, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(166, 5, 26, new Border(Border.TOP | Border.BOTTOM)),
    new Square(167, 5, 27, new Border(Border.TOP | Border.RIGHT)),
    new Square(168, 6, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(169, 6, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(170, 6, 2, new Border(Border.LEFT | Border.RIGHT)),
    new Square(171, 6, 3, new Border(Border.LEFT | Border.RIGHT)),
    new Square(172, 6, 4, new Border(Border.LEFT | Border.RIGHT)),
    new Square(173, 6, 5, new Border(Border.LEFT | Border.RIGHT)),
    new Square(174, 6, 6, new Border(Border.LEFT | Border.RIGHT)),
    new Square(175, 6, 7, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(176, 6, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(177, 6, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(178, 6, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(179, 6, 11, new Border(Border.TOP)),
    new Square(180, 6, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(181, 6, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(182, 6, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(183, 6, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(184, 6, 16, new Border(Border.TOP | Border.RIGHT)),
    new Square(185, 6, 17, new Border(Border.LEFT | Border.RIGHT)),
    new Square(186, 6, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(187, 6, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(188, 6, 20, new Border(Border.LEFT)),
    new Square(189, 6, 21, new Border(Border.NONE)),
    new Square(190, 6, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(191, 6, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(192, 6, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(193, 6, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(194, 6, 26, new Border(Border.TOP | Border.BOTTOM)),
    new Square(195, 6, 27, new Border(Border.RIGHT)),
    new Square(196, 7, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(197, 7, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(198, 7, 2, new Border(Border.LEFT | Border.RIGHT)),
    new Square(199, 7, 3, new Border(Border.LEFT | Border.RIGHT)),
    new Square(200, 7, 4, new Border(Border.LEFT | Border.RIGHT)),
    new Square(201, 7, 5, new Border(Border.LEFT | Border.RIGHT)),
    new Square(202, 7, 6, new Border(Border.LEFT)),
    new Square(203, 7, 7, new Border(Border.TOP | Border.BOTTOM)),
    new Square(204, 7, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(205, 7, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(206, 7, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(207, 7, 11, new Border(Border.BOTTOM)),
    new Square(208, 7, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(209, 7, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(210, 7, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(211, 7, 15, new Border(Border.TOP | Border.RIGHT)),
    new Square(212, 7, 16, new Border(Border.LEFT | Border.RIGHT)),
    new Square(213, 7, 17, new Border(Border.LEFT | Border.RIGHT)),
    new Square(214, 7, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(215, 7, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(216, 7, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(217, 7, 21, new Border(Border.LEFT | Border.RIGHT)),
    new Square(218, 7, 22, new Border(Border.TOP | Border.LEFT)),
    new Square(219, 7, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(220, 7, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(221, 7, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(222, 7, 26, new Border(Border.TOP | Border.BOTTOM)),
    new Square(223, 7, 27, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(224, 8, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(225, 8, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(226, 8, 2, new Border(Border.LEFT | Border.RIGHT)),
    new Square(227, 8, 3, new Border(Border.LEFT | Border.RIGHT)),
    new Square(228, 8, 4, new Border(Border.LEFT | Border.RIGHT)),
    new Square(229, 8, 5, new Border(Border.LEFT | Border.RIGHT)),
    new Square(230, 8, 6, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(231, 8, 7, new Border(Border.TOP | Border.BOTTOM)),
    new Square(232, 8, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(233, 8, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(234, 8, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(235, 8, 11, new Border(Border.TOP | Border.BOTTOM)),
    new Square(236, 8, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(237, 8, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(238, 8, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(239, 8, 15, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(240, 8, 16, new Border(Border.LEFT | Border.RIGHT)),
    new Square(241, 8, 17, new Border(Border.LEFT | Border.RIGHT)),
    new Square(242, 8, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(243, 8, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(244, 8, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(245, 8, 21, new Border(Border.BOTTOM | Border.LEFT | Border.RIGHT)),
    new Square(246, 8, 22, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(247, 8, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(248, 8, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(249, 8, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(250, 8, 26, new Border(Border.TOP | Border.BOTTOM)),
    new Square(251, 8, 27, new Border(Border.TOP | Border.RIGHT)),
    new Square(252, 9, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(253, 9, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(254, 9, 2, new Border(Border.LEFT | Border.RIGHT)),
    new Square(255, 9, 3, new Border(Border.LEFT | Border.RIGHT)),
    new Square(256, 9, 4, new Border(Border.LEFT | Border.RIGHT)),
    new Square(257, 9, 5, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(258, 9, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(259, 9, 7, new Border(Border.TOP | Border.BOTTOM)),
    new Square(260, 9, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(261, 9, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(262, 9, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(263, 9, 11, new Border(Border.TOP | Border.BOTTOM)),
    new Square(264, 9, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(265, 9, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(266, 9, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(267, 9, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(268, 9, 16, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(269, 9, 17, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(270, 9, 18, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(271, 9, 19, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(272, 9, 20, new Border(Border.BOTTOM)),
    new Square(273, 9, 21, new Border(Border.TOP | Border.BOTTOM)),
    new Square(274, 9, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(275, 9, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(276, 9, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(277, 9, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(278, 9, 26, new Border(Border.TOP | Border.RIGHT)),
    new Square(279, 9, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(280, 10, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(281, 10, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(282, 10, 2, new Border(Border.LEFT | Border.RIGHT)),
    new Square(283, 10, 3, new Border(Border.LEFT | Border.RIGHT)),
    new Square(284, 10, 4, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(285, 10, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(286, 10, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(287, 10, 7, new Border(Border.TOP | Border.RIGHT)),
    new Square(288, 10, 8, new Border(Border.TOP | Border.LEFT)),
    new Square(289, 10, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(290, 10, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(291, 10, 11, new Border(Border.TOP | Border.BOTTOM)),
    new Square(292, 10, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(293, 10, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(294, 10, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(295, 10, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(296, 10, 16, new Border(Border.TOP | Border.BOTTOM)),
    new Square(297, 10, 17, new Border(Border.TOP | Border.BOTTOM)),
    new Square(298, 10, 18, new Border(Border.TOP | Border.BOTTOM)),
    new Square(299, 10, 19, new Border(Border.TOP | Border.BOTTOM)),
    new Square(300, 10, 20, new Border(Border.TOP | Border.RIGHT)),
    new Square(301, 10, 21, new Border(Border.TOP | Border.LEFT)),
    new Square(302, 10, 22, new Border(Border.TOP)),
    new Square(303, 10, 23, new Border(Border.TOP | Border.RIGHT)),
    new Square(304, 10, 24, new Border(Border.TOP | Border.LEFT)),
    new Square(305, 10, 25, new Border(Border.TOP | Border.RIGHT)),
    new Square(306, 10, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(307, 10, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(308, 11, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(309, 11, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(310, 11, 2, new Border(Border.LEFT)),
    new Square(311, 11, 3, new Border(Border.NONE)),
    new Square(312, 11, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(313, 11, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(314, 11, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(315, 11, 7, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(316, 11, 8, new Border(Border.LEFT)),
    new Square(317, 11, 9, new Border(Border.TOP)),
    new Square(318, 11, 10, new Border(Border.TOP)),
    new Square(319, 11, 11, new Border(Border.TOP | Border.BOTTOM)),
    new Square(320, 11, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(321, 11, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(322, 11, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(323, 11, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(324, 11, 16, new Border(Border.TOP | Border.BOTTOM)),
    new Square(325, 11, 17, new Border(Border.TOP | Border.BOTTOM)),
    new Square(326, 11, 18, new Border(Border.TOP | Border.BOTTOM)),
    new Square(327, 11, 19, new Border(Border.TOP | Border.RIGHT)),
    new Square(328, 11, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(329, 11, 21, new Border(Border.LEFT | Border.RIGHT)),
    new Square(330, 11, 22, new Border(Border.LEFT | Border.RIGHT)),
    new Square(331, 11, 23, new Border(Border.LEFT | Border.RIGHT)),
    new Square(332, 11, 24, new Border(Border.LEFT | Border.RIGHT)),
    new Square(333, 11, 25, new Border(Border.LEFT | Border.RIGHT)),
    new Square(334, 11, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(335, 11, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(336, 12, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(337, 12, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(338, 12, 2, new Border(Border.LEFT | Border.RIGHT)),
    new Square(339, 12, 3, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(340, 12, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(341, 12, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(342, 12, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(343, 12, 7, new Border(Border.TOP | Border.RIGHT)),
    new Square(344, 12, 8, new Border(Border.LEFT | Border.RIGHT)),
    new Square(345, 12, 9, new Border(Border.LEFT | Border.RIGHT)),
    new Square(346, 12, 10, new Border(Border.LEFT | Border.RIGHT)),
    new Square(347, 12, 11, new Border(Border.TOP | Border.LEFT)),
    new Square(348, 12, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(349, 12, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(350, 12, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(351, 12, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(352, 12, 16, new Border(Border.TOP | Border.RIGHT)),
    new Square(353, 12, 17, new Border(Border.TOP | Border.BOTTOM | Border.LEFT)),
    new Square(354, 12, 18, new Border(Border.TOP | Border.BOTTOM)),
    new Square(355, 12, 19, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(356, 12, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(357, 12, 21, new Border(Border.LEFT | Border.RIGHT)),
    new Square(358, 12, 22, new Border(Border.LEFT | Border.RIGHT)),
    new Square(359, 12, 23, new Border(Border.LEFT | Border.RIGHT)),
    new Square(360, 12, 24, new Border(Border.LEFT | Border.RIGHT)),
    new Square(361, 12, 25, new Border(Border.LEFT | Border.RIGHT)),
    new Square(362, 12, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(363, 12, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(364, 13, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(365, 13, 1, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(366, 13, 2, new Border(Border.BOTTOM)),
    new Square(367, 13, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(368, 13, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(369, 13, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(370, 13, 6, new Border(Border.TOP | Border.RIGHT)),
    new Square(371, 13, 7, new Border(Border.LEFT | Border.RIGHT)),
    new Square(372, 13, 8, new Border(Border.LEFT | Border.RIGHT)),
    new Square(373, 13, 9, new Border(Border.LEFT | Border.RIGHT)),
    new Square(374, 13, 10, new Border(Border.LEFT | Border.RIGHT)),
    new Square(375, 13, 11, new Border(Border.LEFT | Border.RIGHT)),
    new Square(376, 13, 12, new Border(Border.TOP | Border.LEFT), Role.EXTERIOR),
    new Square(377, 13, 13, new Border(Border.TOP), Role.EXTERIOR),
    new Square(378, 13, 14, new Border(Border.TOP), Role.EXTERIOR),
    new Square(379, 13, 15, new Border(Border.TOP | Border.RIGHT), Role.EXTERIOR),
    new Square(380, 13, 16, new Border(Border.LEFT | Border.RIGHT)),
    new Square(381, 13, 17, new Border(Border.TOP | Border.LEFT)),
    new Square(382, 13, 18, new Border(Border.TOP | Border.BOTTOM)),
    new Square(383, 13, 19, new Border(Border.TOP | Border.BOTTOM)),
    new Square(384, 13, 20, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(385, 13, 21, new Border(Border.LEFT | Border.RIGHT)),
    new Square(386, 13, 22, new Border(Border.LEFT | Border.RIGHT)),
    new Square(387, 13, 23, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(388, 13, 24, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(389, 13, 25, new Border(Border.LEFT)),
    new Square(390, 13, 26, new Border(Border.BOTTOM)),
    new Square(391, 13, 27, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(392, 14, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(393, 14, 1, new Border(Border.TOP | Border.LEFT)),
    new Square(394, 14, 2, new Border(Border.TOP | Border.BOTTOM)),
    new Square(395, 14, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(396, 14, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(397, 14, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(398, 14, 6, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(399, 14, 7, new Border(Border.LEFT | Border.RIGHT)),
    new Square(400, 14, 8, new Border(Border.LEFT | Border.RIGHT)),
    new Square(401, 14, 9, new Border(Border.LEFT | Border.RIGHT)),
    new Square(402, 14, 10, new Border(Border.LEFT | Border.RIGHT)),
    new Square(403, 14, 11, new Border(Border.LEFT | Border.RIGHT)),
    new Square(404, 14, 12, new Border(Border.LEFT), Role.EXTERIOR),
    new Square(405, 14, 13, new Border(Border.NONE), Role.EXTERIOR),
    new Square(406, 14, 14, new Border(Border.NONE), Role.EXTERIOR),
    new Square(407, 14, 15, new Border(Border.RIGHT), Role.EXTERIOR),
    new Square(408, 14, 16, new Border(Border.LEFT | Border.RIGHT)),
    new Square(409, 14, 17, new Border(Border.LEFT | Border.RIGHT)),
    new Square(410, 14, 18, new Border(Border.TOP | Border.BOTTOM | Border.LEFT)),
    new Square(411, 14, 19, new Border(Border.TOP | Border.BOTTOM)),
    new Square(412, 14, 20, new Border(Border.TOP | Border.BOTTOM)),
    new Square(413, 14, 21, new Border(Border.RIGHT)),
    new Square(414, 14, 22, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(415, 14, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(416, 14, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(417, 14, 25, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(418, 14, 26, new Border(Border.TOP | Border.LEFT)),
    new Square(419, 14, 27, new Border(Border.TOP | Border.RIGHT)),
    new Square(420, 15, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(421, 15, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(422, 15, 2, new Border(Border.TOP | Border.LEFT)),
    new Square(423, 15, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(424, 15, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(425, 15, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(426, 15, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(427, 15, 7, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(428, 15, 8, new Border(Border.LEFT | Border.RIGHT)),
    new Square(429, 15, 9, new Border(Border.LEFT | Border.RIGHT)),
    new Square(430, 15, 10, new Border(Border.LEFT | Border.RIGHT)),
    new Square(431, 15, 11, new Border(Border.LEFT | Border.RIGHT)),
    new Square(432, 15, 12, new Border(Border.LEFT), Role.EXTERIOR),
    new Square(433, 15, 13, new Border(Border.NONE), Role.EXTERIOR),
    new Square(434, 15, 14, new Border(Border.NONE), Role.EXTERIOR),
    new Square(435, 15, 15, new Border(Border.RIGHT), Role.EXTERIOR),
    new Square(436, 15, 16, new Border(Border.LEFT)),
    new Square(437, 15, 17, new Border(Border.RIGHT)),
    new Square(438, 15, 18, new Border(Border.TOP | Border.LEFT)),
    new Square(439, 15, 19, new Border(Border.TOP | Border.BOTTOM)),
    new Square(440, 15, 20, new Border(Border.TOP | Border.RIGHT)),
    new Square(441, 15, 21, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(442, 15, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(443, 15, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(444, 15, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(445, 15, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(446, 15, 26, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(447, 15, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(448, 16, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(449, 16, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(450, 16, 2, new Border(Border.LEFT | Border.RIGHT)),
    new Square(451, 16, 3, new Border(Border.TOP | Border.LEFT)),
    new Square(452, 16, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(453, 16, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(454, 16, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(455, 16, 7, new Border(Border.TOP | Border.RIGHT)),
    new Square(456, 16, 8, new Border(Border.LEFT | Border.RIGHT)),
    new Square(457, 16, 9, new Border(Border.LEFT | Border.RIGHT)),
    new Square(458, 16, 10, new Border(Border.LEFT | Border.RIGHT)),
    new Square(459, 16, 11, new Border(Border.LEFT | Border.RIGHT)),
    new Square(460, 16, 12, new Border(Border.LEFT), Role.EXTERIOR),
    new Square(461, 16, 13, new Border(Border.NONE), Role.EXTERIOR),
    new Square(462, 16, 14, new Border(Border.NONE), Role.EXTERIOR),
    new Square(463, 16, 15, new Border(Border.RIGHT), Role.EXTERIOR),
    new Square(464, 16, 16, new Border(Border.LEFT | Border.RIGHT)),
    new Square(465, 16, 17, new Border(Border.LEFT | Border.RIGHT)),
    new Square(466, 16, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(467, 16, 19, new Border(Border.TOP | Border.LEFT)),
    new Square(468, 16, 20, new Border(Border.BOTTOM)),
    new Square(469, 16, 21, new Border(Border.TOP | Border.BOTTOM)),
    new Square(470, 16, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(471, 16, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(472, 16, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(473, 16, 25, new Border(Border.TOP)),
    new Square(474, 16, 26, new Border(Border.TOP | Border.RIGHT)),
    new Square(475, 16, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(476, 17, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(477, 17, 1, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(478, 17, 2, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(479, 17, 3, new Border(Border.LEFT | Border.RIGHT)),
    new Square(480, 17, 4, new Border(Border.TOP | Border.LEFT)),
    new Square(481, 17, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(482, 17, 6, new Border(Border.TOP | Border.RIGHT)),
    new Square(483, 17, 7, new Border(Border.LEFT | Border.RIGHT)),
    new Square(484, 17, 8, new Border(Border.LEFT | Border.RIGHT)),
    new Square(485, 17, 9, new Border(Border.LEFT | Border.RIGHT)),
    new Square(486, 17, 10, new Border(Border.LEFT | Border.RIGHT)),
    new Square(487, 17, 11, new Border(Border.LEFT | Border.RIGHT)),
    new Square(488, 17, 12, new Border(Border.BOTTOM | Border.LEFT), Role.EXTERIOR),
    new Square(489, 17, 13, new Border(Border.NONE)),
    new Square(490, 17, 14, new Border(Border.NONE)),
    new Square(491, 17, 15, new Border(Border.BOTTOM | Border.RIGHT), Role.EXTERIOR),
    new Square(492, 17, 16, new Border(Border.LEFT | Border.RIGHT)),
    new Square(493, 17, 17, new Border(Border.LEFT | Border.RIGHT)),
    new Square(494, 17, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(495, 17, 19, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(496, 17, 20, new Border(Border.TOP | Border.BOTTOM)),
    new Square(497, 17, 21, new Border(Border.TOP | Border.BOTTOM)),
    new Square(498, 17, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(499, 17, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(500, 17, 24, new Border(Border.TOP | Border.RIGHT)),
    new Square(501, 17, 25, new Border(Border.LEFT | Border.RIGHT)),
    new Square(502, 17, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(503, 17, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(504, 18, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(505, 18, 1, new Border(Border.TOP | Border.LEFT)),
    new Square(506, 18, 2, new Border(Border.TOP)),
    new Square(507, 18, 3, new Border(Border.NONE)),
    new Square(508, 18, 4, new Border(Border.RIGHT)),
    new Square(509, 18, 5, new Border(Border.TOP | Border.LEFT | Border.RIGHT)),
    new Square(510, 18, 6, new Border(Border.LEFT | Border.RIGHT)),
    new Square(511, 18, 7, new Border(Border.LEFT | Border.RIGHT)),
    new Square(512, 18, 8, new Border(Border.LEFT | Border.RIGHT)),
    new Square(513, 18, 9, new Border(Border.LEFT | Border.RIGHT)),
    new Square(514, 18, 10, new Border(Border.LEFT | Border.RIGHT)),
    new Square(515, 18, 11, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(516, 18, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(517, 18, 13, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(518, 18, 14, new Border(Border.LEFT | Border.RIGHT)),
    new Square(519, 18, 15, new Border(Border.TOP | Border.BOTTOM | Border.LEFT)),
    new Square(520, 18, 16, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(521, 18, 17, new Border(Border.BOTTOM | Border.LEFT | Border.RIGHT)),
    new Square(522, 18, 18, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(523, 18, 19, new Border(Border.TOP | Border.BOTTOM)),
    new Square(524, 18, 20, new Border(Border.TOP | Border.BOTTOM)),
    new Square(525, 18, 21, new Border(Border.TOP | Border.BOTTOM)),
    new Square(526, 18, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(527, 18, 23, new Border(Border.TOP | Border.RIGHT)),
    new Square(528, 18, 24, new Border(Border.LEFT | Border.RIGHT)),
    new Square(529, 18, 25, new Border(Border.LEFT | Border.RIGHT)),
    new Square(530, 18, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(531, 18, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(532, 19, 0, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(533, 19, 1, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(534, 19, 2, new Border(Border.LEFT | Border.RIGHT)),
    new Square(535, 19, 3, new Border(Border.LEFT | Border.RIGHT)),
    new Square(536, 19, 4, new Border(Border.LEFT | Border.RIGHT)),
    new Square(537, 19, 5, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(538, 19, 6, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(539, 19, 7, new Border(Border.LEFT | Border.RIGHT)),
    new Square(540, 19, 8, new Border(Border.LEFT)),
    new Square(541, 19, 9, new Border(Border.RIGHT)),
    new Square(542, 19, 10, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(543, 19, 11, new Border(Border.TOP | Border.BOTTOM)),
    new Square(544, 19, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(545, 19, 13, new Border(Border.TOP | Border.BOTTOM | Border.RIGHT)),
    new Square(546, 19, 14, new Border(Border.LEFT | Border.RIGHT)),
    new Square(547, 19, 15, new Border(Border.TOP | Border.LEFT)),
    new Square(548, 19, 16, new Border(Border.TOP | Border.BOTTOM)),
    new Square(549, 19, 17, new Border(Border.TOP | Border.BOTTOM)),
    new Square(550, 19, 18, new Border(Border.TOP | Border.BOTTOM | Border.RIGHT)),
    new Square(551, 19, 19, new Border(Border.TOP | Border.BOTTOM | Border.LEFT)),
    new Square(552, 19, 20, new Border(Border.TOP | Border.BOTTOM)),
    new Square(553, 19, 21, new Border(Border.TOP | Border.BOTTOM)),
    new Square(554, 19, 22, new Border(Border.TOP | Border.RIGHT)),
    new Square(555, 19, 23, new Border(Border.LEFT | Border.RIGHT)),
    new Square(556, 19, 24, new Border(Border.LEFT | Border.RIGHT)),
    new Square(557, 19, 25, new Border(Border.LEFT | Border.RIGHT)),
    new Square(558, 19, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(559, 19, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(560, 20, 0, new Border(Border.TOP | Border.LEFT)),
    new Square(561, 20, 1, new Border(Border.TOP | Border.BOTTOM)),
    new Square(562, 20, 2, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(563, 20, 3, new Border(Border.LEFT | Border.RIGHT)),
    new Square(564, 20, 4, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(565, 20, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(566, 20, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(567, 20, 7, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(568, 20, 8, new Border(Border.LEFT | Border.RIGHT)),
    new Square(569, 20, 9, new Border(Border.LEFT | Border.RIGHT)),
    new Square(570, 20, 10, new Border(Border.TOP | Border.LEFT)),
    new Square(571, 20, 11, new Border(Border.TOP | Border.BOTTOM)),
    new Square(572, 20, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(573, 20, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(574, 20, 14, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(575, 20, 15, new Border(Border.LEFT | Border.RIGHT)),
    new Square(576, 20, 16, new Border(Border.TOP | Border.LEFT)),
    new Square(577, 20, 17, new Border(Border.TOP | Border.BOTTOM)),
    new Square(578, 20, 18, new Border(Border.TOP | Border.BOTTOM)),
    new Square(579, 20, 19, new Border(Border.TOP | Border.BOTTOM)),
    new Square(580, 20, 20, new Border(Border.TOP | Border.BOTTOM)),
    new Square(581, 20, 21, new Border(Border.TOP | Border.RIGHT)),
    new Square(582, 20, 22, new Border(Border.LEFT | Border.RIGHT)),
    new Square(583, 20, 23, new Border(Border.LEFT | Border.RIGHT)),
    new Square(584, 20, 24, new Border(Border.LEFT | Border.RIGHT)),
    new Square(585, 20, 25, new Border(Border.LEFT | Border.RIGHT)),
    new Square(586, 20, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(587, 20, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(588, 21, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(589, 21, 1, new Border(Border.TOP | Border.LEFT)),
    new Square(590, 21, 2, new Border(Border.TOP | Border.BOTTOM)),
    new Square(591, 21, 3, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(592, 21, 4, new Border(Border.TOP | Border.LEFT)),
    new Square(593, 21, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(594, 21, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(595, 21, 7, new Border(Border.TOP | Border.BOTTOM)),
    new Square(596, 21, 8, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(597, 21, 9, new Border(Border.LEFT | Border.RIGHT)),
    new Square(598, 21, 10, new Border(Border.LEFT | Border.RIGHT)),
    new Square(599, 21, 11, new Border(Border.TOP | Border.LEFT)),
    new Square(600, 21, 12, new Border(Border.TOP | Border.RIGHT)),
    new Square(601, 21, 13, new Border(Border.TOP | Border.LEFT)),
    new Square(602, 21, 14, new Border(Border.TOP | Border.RIGHT)),
    new Square(603, 21, 15, new Border(Border.LEFT | Border.RIGHT)),
    new Square(604, 21, 16, new Border(Border.LEFT | Border.RIGHT)),
    new Square(605, 21, 17, new Border(Border.TOP | Border.LEFT)),
    new Square(606, 21, 18, new Border(Border.TOP | Border.BOTTOM)),
    new Square(607, 21, 19, new Border(Border.TOP | Border.BOTTOM)),
    new Square(608, 21, 20, new Border(Border.TOP | Border.RIGHT)),
    new Square(609, 21, 21, new Border(Border.LEFT | Border.RIGHT)),
    new Square(610, 21, 22, new Border(Border.LEFT | Border.RIGHT)),
    new Square(611, 21, 23, new Border(Border.LEFT | Border.RIGHT)),
    new Square(612, 21, 24, new Border(Border.LEFT | Border.RIGHT)),
    new Square(613, 21, 25, new Border(Border.LEFT | Border.RIGHT)),
    new Square(614, 21, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(615, 21, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(616, 22, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(617, 22, 1, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(618, 22, 2, new Border(Border.TOP | Border.BOTTOM)),
    new Square(619, 22, 3, new Border(Border.TOP | Border.RIGHT)),
    new Square(620, 22, 4, new Border(Border.LEFT | Border.RIGHT)),
    new Square(621, 22, 5, new Border(Border.TOP | Border.LEFT)),
    new Square(622, 22, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(623, 22, 7, new Border(Border.TOP | Border.BOTTOM)),
    new Square(624, 22, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(625, 22, 9, new Border(Border.RIGHT)),
    new Square(626, 22, 10, new Border(Border.LEFT | Border.RIGHT)),
    new Square(627, 22, 11, new Border(Border.LEFT | Border.RIGHT)),
    new Square(628, 22, 12, new Border(Border.LEFT | Border.RIGHT)),
    new Square(629, 22, 13, new Border(Border.LEFT | Border.RIGHT)),
    new Square(630, 22, 14, new Border(Border.LEFT | Border.RIGHT)),
    new Square(631, 22, 15, new Border(Border.LEFT | Border.RIGHT)),
    new Square(632, 22, 16, new Border(Border.LEFT | Border.RIGHT)),
    new Square(633, 22, 17, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(634, 22, 18, new Border(Border.TOP | Border.RIGHT)),
    new Square(635, 22, 19, new Border(Border.TOP | Border.LEFT)),
    new Square(636, 22, 20, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(637, 22, 21, new Border(Border.LEFT | Border.RIGHT)),
    new Square(638, 22, 22, new Border(Border.LEFT | Border.RIGHT)),
    new Square(639, 22, 23, new Border(Border.LEFT)),
    new Square(640, 22, 24, new Border(Border.RIGHT)),
    new Square(641, 22, 25, new Border(Border.LEFT | Border.RIGHT)),
    new Square(642, 22, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(643, 22, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(644, 23, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(645, 23, 1, new Border(Border.TOP | Border.BOTTOM | Border.LEFT)),
    new Square(646, 23, 2, new Border(Border.TOP | Border.BOTTOM)),
    new Square(647, 23, 3, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(648, 23, 4, new Border(Border.LEFT | Border.RIGHT)),
    new Square(649, 23, 5, new Border(Border.LEFT)),
    new Square(650, 23, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(651, 23, 7, new Border(Border.TOP | Border.BOTTOM)),
    new Square(652, 23, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(653, 23, 9, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(654, 23, 10, new Border(Border.LEFT | Border.RIGHT)),
    new Square(655, 23, 11, new Border(Border.LEFT | Border.RIGHT)),
    new Square(656, 23, 12, new Border(Border.LEFT | Border.RIGHT)),
    new Square(657, 23, 13, new Border(Border.LEFT | Border.RIGHT)),
    new Square(658, 23, 14, new Border(Border.LEFT | Border.RIGHT)),
    new Square(659, 23, 15, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(660, 23, 16, new Border(Border.NONE)),
    new Square(661, 23, 17, new Border(Border.TOP | Border.RIGHT)),
    new Square(662, 23, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(663, 23, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(664, 23, 20, new Border(Border.TOP | Border.LEFT)),
    new Square(665, 23, 21, new Border(Border.RIGHT)),
    new Square(666, 23, 22, new Border(Border.LEFT | Border.RIGHT)),
    new Square(667, 23, 23, new Border(Border.LEFT | Border.RIGHT)),
    new Square(668, 23, 24, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(669, 23, 25, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(670, 23, 26, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(671, 23, 27, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(672, 24, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(673, 24, 1, new Border(Border.TOP | Border.LEFT | Border.RIGHT)),
    new Square(674, 24, 2, new Border(Border.TOP | Border.LEFT)),
    new Square(675, 24, 3, new Border(Border.TOP | Border.RIGHT)),
    new Square(676, 24, 4, new Border(Border.LEFT | Border.RIGHT)),
    new Square(677, 24, 5, new Border(Border.LEFT | Border.RIGHT)),
    new Square(678, 24, 6, new Border(Border.TOP | Border.LEFT)),
    new Square(679, 24, 7, new Border(Border.TOP | Border.BOTTOM)),
    new Square(680, 24, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(681, 24, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(682, 24, 10, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(683, 24, 11, new Border(Border.LEFT | Border.RIGHT)),
    new Square(684, 24, 12, new Border(Border.LEFT | Border.RIGHT)),
    new Square(685, 24, 13, new Border(Border.LEFT | Border.RIGHT)),
    new Square(686, 24, 14, new Border(Border.LEFT)),
    new Square(687, 24, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(688, 24, 16, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(689, 24, 17, new Border(Border.LEFT | Border.RIGHT)),
    new Square(690, 24, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(691, 24, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(692, 24, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(693, 24, 21, new Border(Border.LEFT | Border.RIGHT)),
    new Square(694, 24, 22, new Border(Border.LEFT | Border.RIGHT)),
    new Square(695, 24, 23, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(696, 24, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(697, 24, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(698, 24, 26, new Border(Border.TOP | Border.BOTTOM)),
    new Square(699, 24, 27, new Border(Border.TOP | Border.RIGHT)),
    new Square(700, 25, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(701, 25, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(702, 25, 2, new Border(Border.LEFT | Border.RIGHT)),
    new Square(703, 25, 3, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(704, 25, 4, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(705, 25, 5, new Border(Border.LEFT | Border.RIGHT)),
    new Square(706, 25, 6, new Border(Border.LEFT | Border.RIGHT)),
    new Square(707, 25, 7, new Border(Border.TOP | Border.LEFT)),
    new Square(708, 25, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(709, 25, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(710, 25, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(711, 25, 11, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(712, 25, 12, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(713, 25, 13, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(714, 25, 14, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(715, 25, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(716, 25, 16, new Border(Border.TOP | Border.RIGHT)),
    new Square(717, 25, 17, new Border(Border.LEFT | Border.RIGHT)),
    new Square(718, 25, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(719, 25, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(720, 25, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(721, 25, 21, new Border(Border.LEFT | Border.RIGHT)),
    new Square(722, 25, 22, new Border(Border.LEFT)),
    new Square(723, 25, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(724, 25, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(725, 25, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(726, 25, 26, new Border(Border.TOP | Border.RIGHT)),
    new Square(727, 25, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(728, 26, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(729, 26, 1, new Border(Border.LEFT)),
    new Square(730, 26, 2, new Border(Border.BOTTOM)),
    new Square(731, 26, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(732, 26, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(733, 26, 5, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(734, 26, 6, new Border(Border.LEFT | Border.RIGHT)),
    new Square(735, 26, 7, new Border(Border.LEFT | Border.RIGHT)),
    new Square(736, 26, 8, new Border(Border.TOP | Border.LEFT)),
    new Square(737, 26, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(738, 26, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(739, 26, 11, new Border(Border.TOP)),
    new Square(740, 26, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(741, 26, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(742, 26, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(743, 26, 15, new Border(Border.TOP | Border.RIGHT)),
    new Square(744, 26, 16, new Border(Border.LEFT | Border.RIGHT)),
    new Square(745, 26, 17, new Border(Border.LEFT | Border.RIGHT)),
    new Square(746, 26, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(747, 26, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(748, 26, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(749, 26, 21, new Border(Border.LEFT)),
    new Square(750, 26, 22, new Border(Border.NONE)),
    new Square(751, 26, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(752, 26, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(753, 26, 25, new Border(Border.TOP | Border.BOTTOM)),
    new Square(754, 26, 26, new Border(Border.RIGHT)),
    new Square(755, 26, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(756, 27, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(757, 27, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(758, 27, 2, new Border(Border.TOP | Border.LEFT)),
    new Square(759, 27, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(760, 27, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(761, 27, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(762, 27, 6, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(763, 27, 7, new Border(Border.LEFT | Border.RIGHT)),
    new Square(764, 27, 8, new Border(Border.LEFT | Border.RIGHT)),
    new Square(765, 27, 9, new Border(Border.TOP | Border.BOTTOM | Border.LEFT)),
    new Square(766, 27, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(767, 27, 11, new Border(Border.BOTTOM)),
    new Square(768, 27, 12, new Border(Border.TOP | Border.BOTTOM)),
    new Square(769, 27, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(770, 27, 14, new Border(Border.TOP | Border.RIGHT)),
    new Square(771, 27, 15, new Border(Border.LEFT | Border.RIGHT)),
    new Square(772, 27, 16, new Border(Border.LEFT | Border.RIGHT)),
    new Square(773, 27, 17, new Border(Border.LEFT | Border.RIGHT)),
    new Square(774, 27, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(775, 27, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(776, 27, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(777, 27, 21, new Border(Border.LEFT | Border.RIGHT)),
    new Square(778, 27, 22, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(779, 27, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(780, 27, 24, new Border(Border.TOP | Border.BOTTOM)),
    new Square(781, 27, 25, new Border(Border.TOP | Border.RIGHT)),
    new Square(782, 27, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(783, 27, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(784, 28, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(785, 28, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(786, 28, 2, new Border(Border.LEFT | Border.RIGHT)),
    new Square(787, 28, 3, new Border(Border.TOP | Border.BOTTOM | Border.LEFT)),
    new Square(788, 28, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(789, 28, 5, new Border(Border.TOP | Border.BOTTOM)),
    new Square(790, 28, 6, new Border(Border.TOP | Border.BOTTOM)),
    new Square(791, 28, 7, new Border(Border.NONE)),
    new Square(792, 28, 8, new Border(Border.NONE)),
    new Square(793, 28, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(794, 28, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(795, 28, 11, new Border(Border.TOP | Border.BOTTOM)),
    new Square(796, 28, 12, new Border(Border.TOP)),
    new Square(797, 28, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(798, 28, 14, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(799, 28, 15, new Border(Border.LEFT | Border.RIGHT)),
    new Square(800, 28, 16, new Border(Border.BOTTOM | Border.LEFT | Border.RIGHT)),
    new Square(801, 28, 17, new Border(Border.LEFT | Border.RIGHT)),
    new Square(802, 28, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(803, 28, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(804, 28, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(805, 28, 21, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(806, 28, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(807, 28, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(808, 28, 24, new Border(Border.TOP | Border.RIGHT)),
    new Square(809, 28, 25, new Border(Border.LEFT | Border.RIGHT)),
    new Square(810, 28, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(811, 28, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(812, 29, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(813, 29, 1, new Border(Border.LEFT | Border.RIGHT)),
    new Square(814, 29, 2, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(815, 29, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(816, 29, 4, new Border(Border.TOP | Border.BOTTOM)),
    new Square(817, 29, 5, new Border(Border.TOP | Border.RIGHT)),
    new Square(818, 29, 6, new Border(Border.TOP | Border.LEFT)),
    new Square(819, 29, 7, new Border(Border.RIGHT)),
    new Square(820, 29, 8, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(821, 29, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(822, 29, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(823, 29, 11, new Border(Border.TOP | Border.RIGHT)),
    new Square(824, 29, 12, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(825, 29, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(826, 29, 14, new Border(Border.TOP | Border.RIGHT)),
    new Square(827, 29, 15, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(828, 29, 16, new Border(Border.TOP | Border.RIGHT)),
    new Square(829, 29, 17, new Border(Border.BOTTOM | Border.LEFT | Border.RIGHT)),
    new Square(830, 29, 18, new Border(Border.LEFT | Border.RIGHT)),
    new Square(831, 29, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(832, 29, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(833, 29, 21, new Border(Border.TOP | Border.LEFT)),
    new Square(834, 29, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(835, 29, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(836, 29, 24, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(837, 29, 25, new Border(Border.LEFT | Border.RIGHT)),
    new Square(838, 29, 26, new Border(Border.LEFT | Border.RIGHT)),
    new Square(839, 29, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(840, 30, 0, new Border(Border.LEFT | Border.RIGHT)),
    new Square(841, 30, 1, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(842, 30, 2, new Border(Border.TOP | Border.BOTTOM)),
    new Square(843, 30, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(844, 30, 4, new Border(Border.TOP | Border.RIGHT)),
    new Square(845, 30, 5, new Border(Border.LEFT | Border.RIGHT)),
    new Square(846, 30, 6, new Border(Border.LEFT | Border.RIGHT)),
    new Square(847, 30, 7, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(848, 30, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(849, 30, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(850, 30, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(851, 30, 11, new Border(Border.RIGHT)),
    new Square(852, 30, 12, new Border(Border.TOP | Border.LEFT)),
    new Square(853, 30, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(854, 30, 14, new Border(Border.BOTTOM)),
    new Square(855, 30, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(856, 30, 16, new Border(Border.BOTTOM)),
    new Square(857, 30, 17, new Border(Border.TOP | Border.BOTTOM)),
    new Square(858, 30, 18, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(859, 30, 19, new Border(Border.LEFT | Border.RIGHT)),
    new Square(860, 30, 20, new Border(Border.LEFT | Border.RIGHT)),
    new Square(861, 30, 21, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(862, 30, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(863, 30, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(864, 30, 24, new Border(Border.TOP | Border.RIGHT)),
    new Square(865, 30, 25, new Border(Border.LEFT | Border.RIGHT)),
    new Square(866, 30, 26, new Border(Border.BOTTOM | Border.LEFT | Border.RIGHT)),
    new Square(867, 30, 27, new Border(Border.LEFT | Border.RIGHT)),
    new Square(868, 31, 0, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(869, 31, 1, new Border(Border.TOP | Border.BOTTOM)),
    new Square(870, 31, 2, new Border(Border.TOP | Border.BOTTOM)),
    new Square(871, 31, 3, new Border(Border.TOP | Border.BOTTOM)),
    new Square(872, 31, 4, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(873, 31, 5, new Border(Border.LEFT | Border.RIGHT), Role.EXIT),
    new Square(874, 31, 6, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(875, 31, 7, new Border(Border.TOP | Border.BOTTOM)),
    new Square(876, 31, 8, new Border(Border.TOP | Border.BOTTOM)),
    new Square(877, 31, 9, new Border(Border.TOP | Border.BOTTOM)),
    new Square(878, 31, 10, new Border(Border.TOP | Border.BOTTOM)),
    new Square(879, 31, 11, new Border(Border.BOTTOM)),
    new Square(880, 31, 12, new Border(Border.BOTTOM)),
    new Square(881, 31, 13, new Border(Border.TOP | Border.BOTTOM)),
    new Square(882, 31, 14, new Border(Border.TOP | Border.BOTTOM)),
    new Square(883, 31, 15, new Border(Border.TOP | Border.BOTTOM)),
    new Square(884, 31, 16, new Border(Border.TOP | Border.BOTTOM)),
    new Square(885, 31, 17, new Border(Border.TOP | Border.BOTTOM)),
    new Square(886, 31, 18, new Border(Border.TOP), Role.ENTRANCE),
    new Square(887, 31, 19, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(888, 31, 20, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(889, 31, 21, new Border(Border.TOP | Border.BOTTOM)),
    new Square(890, 31, 22, new Border(Border.TOP | Border.BOTTOM)),
    new Square(891, 31, 23, new Border(Border.TOP | Border.BOTTOM)),
    new Square(892, 31, 24, new Border(Border.BOTTOM | Border.RIGHT)),
    new Square(893, 31, 25, new Border(Border.BOTTOM | Border.LEFT)),
    new Square(894, 31, 26, new Border(Border.TOP | Border.BOTTOM)),
    new Square(895, 31, 27, new Border(Border.BOTTOM | Border.RIGHT))
]

export { squares }